### ISSUE TITLE
1.19.3 support

### ISSUE THREAD

**Issue by RoonMoonlight** [FoundationGames/Animatica#27]
Title says it all

**Comment by RoonMoonlight** [comment]
Are you there? Is there any plan to support 1.19.3

**Comment by EGOIST1372** [comment]
@FoundationGames any updates in this matter?
thanks in advance <3

**Comment by Cloudperry** [comment]
The previous version seems to work just fine on 1.19.3. I made a PR anyway to bump the version and update Fabric things.

The updated version is [here](https://github.com/Cloudperry/Animatica/releases/tag/1.19.3) or you can just use the most recent version on Modrinth and it will probably work.

**Comment by RoonMoonlight** [comment]
> The previous version seems to work just fine on 1.19.3. I made a PR anyway to bump the version and update Fabric things.
> 
> The updated version is [here](https://github.com/Cloudperry/Animatica/releases/tag/1.19.3) or you can just use the most recent version on Modrinth and it will probably work.

Really? Thanks for test result!

I thought this mod wouldn't be working due to recent 1.19.3 changes... Glad to see this mod works well on 1.19.3

Since the author of the mod is inactive, I'm kinda worried about the future of this mod... Not sure why FoundationGames went inactive maintaining this mod

**Comment by FoundationGames** [comment]
The mod works fine on 1.19-1.19.3 and any potential bug fixes that don't require me to touch more of Minecraft's code shouldn't be restricted to a 1.19.3-specific release. The reasons why Animatica is a rare case in this regard mostly boil down to "I only touch Minecraft in a couple of places"
Additionally, as far as open source projects go, 6 months of inactivity is not abandonment - especially when the CurseForge page is being updated to denote compatibility with new versions. This project, along with 6+ others, are worked on in spare time.
**Side Note:** The reason why I didn't update the CF version sooner is due to the volume of "Update to 1.19.3" requests I have been receiving, without anybody actually testing the mod and confirming to me that it is broken (which it isn't)
